Update depoly.yml

diff --git a/.github/workflows/depoly.yml b/.github/workflows/depoly.yml
--- a/.github/workflows/depoly.yml
+++ b/.github/workflows/depoly.yml
@@ -42,16 +42,18 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      - name: Deploy to Azure Container Instance
+      - name: Deploy to Azure Container Instance with retry
         run: |
-          az container create \
-            --resource-group $AZURE_RESOURCE_GROUP \
-            --name $AZURE_CONTAINER_NAME \
-            --image ${{ secrets.DOCKERHUB_USERNAME }}/mandelazz:latest \
-            --dns-name-label mandelazz-api-label \
-            --ports 80 443 \
-            --location $AZURE_LOCATION \
-            --restart-policy OnFailure \
-            --os-type Linux \
-            --cpu 1 \
-            --memory 1.5
+          for i in {1..3}; do
+            az container create \
+              --resource-group $AZURE_RESOURCE_GROUP \
+              --name $AZURE_CONTAINER_NAME \
+              --image ${{ secrets.DOCKERHUB_USERNAME }}/mandelazz:latest \
+              --dns-name-label mandelazz-api-label \
+              --ports 80 443 \
+              --location $AZURE_LOCATION \
+              --restart-policy OnFailure \
+              --os-type Linux \
+              --cpu 1 \
+              --memory 1.5 && break || echo "Attempt $i failed, retrying..." && sleep 10
+          done
